# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/mentoring"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependency updates"
    open-pull-requests-limit: 2
    reviewers:
      - "nhavronskyi"
  - package-ecosystem: "maven"
    directory: "/bobocode"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependency updates"
    open-pull-requests-limit: 2
    reviewers:
      - "nhavronskyi"
