services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_USERNAME}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

