name: Build Check for Spring Boot Projects

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Workspace
        id: set-workspace
        run: echo "workspace=$(pwd)" >> $GITHUB_OUTPUT

  maven-build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: 23
    steps:
      - name: Checkout code (using workspace)
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Maven Build
        working-directory: /bobocode
        run: ./mvnw clean package

  gradle-build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: 23
    steps:
      - name: Checkout code (using workspace)
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Gradle Build
        working-directory: /mentoring
        run: ./gradlew build