name: Build Check for Spring Boot Projects

on:
  pull_request:
    branches:
      - '*'

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      workspace: ${{ steps.set-workspace.outputs.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Workspace
        id: set-workspace
        run: echo "workspace=$(pwd)" >> $GITHUB_OUTPUT
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

  maven-build:
    needs: prepare
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code again (needed for each job)
        uses: actions/checkout@v4
      - name: Maven Build
        working-directory: ${{ needs.prepare.outputs.workspace }}/learning-java/bobocode
        run: ./mvnw package -X

  gradle-build:
    needs: prepare
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code again (needed for each job)
        uses: actions/checkout@v4
      - name: Gradle Build
        working-directory: ${{ needs.prepare.outputs.workspace }}/learning-java/mentoring
        run: ./gradlew build
