name: Build Check for Spring Boot Projects

on:
  push:
    branches:
      - *
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: build bobocode
        run: |
          cd bobocode/
          ./mvnw clean package;

      - name: build mentoring
        run: |
          cd mentoring/
          ./gradlew build;
