name: Build Check for Spring Boot Projects

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Install Gradle
        run: sudo apt-get install -y gradle

      - name: Find and build Maven projects
        run: |
          find . -name "pom.xml" -execked mvn clean install -B \;

      - name: Find and build Gradle projects
        run: |
          find . -name "build.gradle" -execked gradle build --no-daemon \;
